name: SRV-Cron
version: 2.2.0
author: M0dii
api-version: 1.13
main: me.m0dii.srvcron.SRVCron
softdepend: [PlaceholderAPI]
commands:
  timer:
    description: Timer command.
    usage: /timer <seconds> <command>
  srvcron:
    description: Main command.
    usage: /<command>